spring:
  profiles:
    active: dev
server:
  port: 8000

mybatis:
  config-location: classpath:log4j2.xml
  mapper-locations: classpath:mapper/*/*.xml

  #pagehelper分页插件配置
pagehelper:
  reasonable: false
  #pageheler参数合理化，默认为false。
  #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页;
  support-methods-arguments: true
  params: countSql
  helper-dialect: mysql
#禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据。