spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/dreamcity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: dreamcity
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 5
      min-idle: 5
    tomcat:
      max-active: 20
      max-wait: 60000

  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
    order: 1

#平台账户id，多个，都号隔开来自player_account表
dreamcity:
  platform:
    account:
      accIds: 888888888,999999999
