spring:
  application:
    name: city-backend
  profiles:
    active: dev

server:
  port: 8000
  servlet:
    context-path: /

#mybatis:
#  config-location: classpath:log4j2.xml
#  type-aliases-package: com.dream.city.*.dao
#  mapper-locations: classpath:mapper/*/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
#pagehelper:
#  reasonable: false
#  support-methods-arguments: true
#  params: countSql
#  helper-dialect: mysql