server:
  port: 8001
  servlet:
    context-path: /

spring:
  application:
    name: city-backend
  profiles:
    active: ${spring.profiles.active}


mybatis:
  type-aliases-package: com.dream.city.base.model.mapper
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: countSql
  helper-dialect: mysql















